能否加入 Azure OpenAI 的相关支持 #471
ikechan8370/chatgpt-plugin pull request #536
Opened 2023-08-02 02:27 UTC by sigeisment

1.参数配置
azureUrl:端点地址，https://xxxx.openai.azure.com/
azureDeploymentName: chatgpt部署名
apiKey：管理密钥
2.增加`#chatgpt切换azure`命令切换成azure模式

2023-08-08 06:23 UTC, Xcating commented
增加锅巴支持

2023-08-08 06:54 UTC, Xcating requested changes
package.json 需要加入依赖 @azure/openai 方便用户安装 (?)

2023-08-09 14:46 UTC, ikechan8370 commented on apps/chat.js
> +import { OpenAIClient, AzureKeyCredential } from '@azure/openai'
由于引入新依赖，需要做一下引用判断，保证不用azure的用户更新了插件也不会报错导致加载失败

2023-08-24 14:35 UTC, ikechan8370 approved these changes

2023-08-24 14:35 UTC, merged